### PR TITLE
fix for gradient norm reduction

### PR DESCRIPTION
**Pull request by fabiolrdiniz**
## Description
The SaddlePointMinimizer.h was reading the gradient norm reduction from the YAML as a double but storing it as an integer.

### Issue(s) addressed
- fixes #https://github.com/JCSDA-internal/oops/issues/924

## Dependencies
none

## Impact
none

### CODE REVIEW

**Review by ytremolet — APPROVED** [review]
Good fix, thanks.
We'll merge as soon as the CI testing is up and running.

**Comment by fabiolrdiniz** [comment]
> Good fix, thanks.
> We'll merge as soon as the CI testing is up and running.

Thanks, @ytremolet! Happy to help.

**Review by shlyaeva — APPROVED** [review]
good catch!

**Comment by fabiolrdiniz** [comment]
> good catch!

Thanks, @shlyaeva!

**Comment by mer-a-o** [comment]
@fabiolrdiniz sorry for debugging the issue with CI testing in your PR. Please ignore all my commits.

**Comment by mer-a-o** [comment]
@ytremolet, I think the issue with getting the branch name in CodeBuild is solved in this PR.

**Comment by fabiolrdiniz** [comment]
> @fabiolrdiniz sorry for debugging the issue with CI testing in your PR. Please ignore all my commits.

No problem, @mer-a-o! I believe that was the intention of @ytremolet to test the procedure.

**Comment by mer-a-o** [comment]
@ytremolet I have disabled Travis-CI fo jcsda public for now. So we can ignore the failure in Travis-CI and merge this PR.

**Comment by ytremolet** [comment]
Thanks.

**Pull request merged**
