### PR TITLE
Set version in project line

### PR DESCRIPTION
**Pull request by ytremolet**
Easy activity points!

### CODE REVIEW

**Review by shlyaeva — APPROVED** [review]
🎉

**Comment by shlyaeva** [comment]
woo-hoo, codecov is back and oops is now above 90% covered! (must be recent removal of UnstructuredGrid-related files that were 0% tested that got us over 90%).

**Comment by mmiesch** [comment]
> woo-hoo, codecov is back and oops is now above 90% covered! (must be recent removal of UnstructuredGrid-related files that were 0% tested that got us over 90%).

Yeah - I was thinking of mentioning some of those codecov numbers in the quarterly review slides in relation to the testing sprint but it was temporarily offline

**Comment by ytremolet** [comment]
Closing because replaced by #16

**Pull request closed without merging**
