### PR TITLE
Bump version to 1.0.0 for release

### PR DESCRIPTION
**Pull request by rhoneyager**
This PR updates the version number in the repository.

### CODE REVIEW

**Review by ytremolet — CHANGES_REQUESTED** [review]
I think we should do that in the release branches when we are ready.

**Comment by shlyaeva** [comment]
> I think we should do that in the release branches when we are ready.

Will we merge those back into develop? Develop would have to have updated versions too, I think.

**Comment by ytremolet** [comment]
Yes, release branches go to master and develop.

**Review by shlyaeva — APPROVED** [review]

**Review by srherbener — APPROVED** [review]

**Comment by danholdaway** [comment]
I think this can be closed now

**Pull request closed without merging**
