### PR TITLE
update doxyfile

### PR DESCRIPTION
**Pull request by mmiesch**
## Description

Updates the doxyfile for generating doxygen documentation

## Definition of Done

doxygen v 1.8.18+ runs without throwing warnings

### CODE REVIEW

**Review by srherbener — APPROVED** [review]

**Review by ytremolet — APPROVED** [review]
Thanks!

**Review by rhoneyager — APPROVED** [review]
Looks good. Oddly, the [oops namespace documentation](http://data.jcsda.org/doxygen/Release/1.0/oops/namespaceoops.html#details) describes oops as the "Local Ensemble Tranform Kalman Filter solver".

**Comment by ytremolet** [comment]
Can you regenerate the page with the latest commit?

**Comment by mmiesch** [comment]
> Can you regenerate the page with the latest commit?

Sorry - got distracted - check now - should be updated

**Comment by mmiesch** [comment]
> > Can you regenerate the page with the latest commit?
> 
> Sorry - got distracted - check now - should be updated

http://data.jcsda.org/doxygen/Release/1.0/oops/index.html

**Comment by ytremolet** [comment]
No problem, thanks.

**Pull request merged**
