### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by mer-a-o**
## Description
 Update CI for public release. 
ecwmf repos use jcsda-internal for now

### CODE REVIEW

**Review by ytremolet — APPROVED** [review]
Thanks.

**Review by mmiesch — APPROVED** [review]
Great! Thanks!

**Comment by benjaminmenetrier** [comment]
@mer-a-o: should I do the same for SABER, or are you working on it?

**Comment by mer-a-o** [comment]
@benjaminmenetrier, I am working on it. I will work from https://github.com/JCSDA/saber/pull/7 .

**Pull request merged**
